apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    uid: postgres
    url: postgres:5432
    database: farm_dwh
    user: spark_user
    secureJsonData:
      password: spark_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
